"""Curated, real Indian government schemes for farmers with official source links.
Only verified, well-known central schemes are included. Benefits/eligibility are
described in high-level, farmer-friendly language. Always direct users to official source."""

SCHEMES = [
    {
        "id": "pm-kisan",
        "name": "PM-KISAN (Pradhan Mantri Kisan Samman Nidhi)",
        "category": "Income Support",
        "what": "A central scheme that gives eligible small and marginal farmer families direct income support to help with farming and household needs.",
        "eligibility": "Landholding farmer families. Certain higher-income groups and government employees are excluded. Verify current rules on the official portal.",
        "benefit": "Rs. 6,000 per year paid in three equal installments directly into the bank account (as per official PM-KISAN portal).",
        "documents": ["Aadhaar card", "Bank account details", "Land record details"],
        "how_to_apply": "Register through the official PM-KISAN portal or your local Common Service Centre (CSC) / village revenue officer.",
        "deadline": None,
        "official_source": "https://pmkisan.gov.in",
        "crops": ["all"],
        "states": ["all"],
        "keywords": ["income", "support", "money", "cash", "samman nidhi"],
    },
    {
        "id": "pmfby",
        "name": "PMFBY (Pradhan Mantri Fasal Bima Yojana)",
        "category": "Crop Insurance",
        "what": "A crop insurance scheme that protects farmers against crop loss due to natural calamities, pests and diseases.",
        "eligibility": "Farmers growing notified crops in notified areas, including sharecroppers and tenant farmers. Verify notified crops for your area.",
        "benefit": "Insurance payout for crop loss. Farmers pay a low premium (2% for Kharif, 1.5% for Rabi food/oilseed crops, 5% for commercial/horticultural crops).",
        "documents": ["Aadhaar card", "Bank account details", "Land records / sowing certificate", "Loan details if applicable"],
        "how_to_apply": "Apply through banks, insurance companies, CSCs, or the National Crop Insurance Portal.",
        "deadline": None,
        "official_source": "https://pmfby.gov.in",
        "crops": ["all"],
        "states": ["all"],
        "keywords": ["insurance", "crop loss", "bima", "calamity", "flood", "drought"],
    },
    {
        "id": "kcc",
        "name": "Kisan Credit Card (KCC)",
        "category": "Credit / Loan",
        "what": "Provides farmers with timely and affordable credit for cultivation and other needs through a simple credit card.",
        "eligibility": "Farmers (individual/joint owner cultivators), tenant farmers, oral lessees and sharecroppers. Verify with your bank.",
        "benefit": "Short-term crop loans at concessional interest rates, with interest subvention for prompt repayment (as per official guidelines).",
        "documents": ["Identity proof (Aadhaar)", "Address proof", "Land documents", "Passport photo"],
        "how_to_apply": "Apply at any commercial bank, cooperative bank or regional rural bank branch.",
        "deadline": None,
        "official_source": "https://www.myscheme.gov.in/schemes/kcc",
        "crops": ["all"],
        "states": ["all"],
        "keywords": ["loan", "credit", "money", "card", "interest"],
    },
    {
        "id": "shc",
        "name": "Soil Health Card Scheme",
        "category": "Soil Health",
        "what": "Provides farmers with a soil health card showing the nutrient status of their soil and recommendations on fertilizer use.",
        "eligibility": "All farmers can get their soil tested under the scheme.",
        "benefit": "Free soil testing and crop-wise recommendations to improve soil health and reduce fertilizer cost.",
        "documents": ["Land details", "Farmer identity proof"],
        "how_to_apply": "Contact your local agriculture department or soil testing lab. Check the official portal for centres.",
        "deadline": None,
        "official_source": "https://soilhealth.dac.gov.in",
        "crops": ["all"],
        "states": ["all"],
        "keywords": ["soil", "fertilizer", "nutrient", "testing", "health"],
    },
    {
        "id": "pmksy",
        "name": "PMKSY (Pradhan Mantri Krishi Sinchayee Yojana)",
        "category": "Irrigation",
        "what": "Aims to expand cultivable area under assured irrigation and improve water use efficiency ('Per Drop More Crop').",
        "eligibility": "Farmers seeking micro-irrigation (drip/sprinkler) support. Implemented via state agriculture/horticulture departments.",
        "benefit": "Subsidy on micro-irrigation systems like drip and sprinkler irrigation (subsidy rates vary by state and category).",
        "documents": ["Land records", "Bank account", "Identity proof"],
        "how_to_apply": "Apply through your state agriculture / horticulture department or the official PMKSY portal.",
        "deadline": None,
        "official_source": "https://pmksy.gov.in",
        "crops": ["all"],
        "states": ["all"],
        "keywords": ["irrigation", "water", "drip", "sprinkler", "sinchayee"],
    },
    {
        "id": "pm-kusum",
        "name": "PM-KUSUM (Solar Pumps for Farmers)",
        "category": "Energy / Irrigation",
        "what": "Supports farmers to install solar pumps and grid-connected solar power plants to reduce diesel/electricity dependence.",
        "eligibility": "Individual farmers, cooperatives, panchayats and farmer producer organisations. Verify state-specific components.",
        "benefit": "Subsidy support for standalone solar pumps and solarisation of existing pumps (central + state subsidy as per guidelines).",
        "documents": ["Land records", "Bank account", "Aadhaar", "Electricity connection details if applicable"],
        "how_to_apply": "Apply through your state nodal agency / DISCOM or the official PM-KUSUM portal.",
        "deadline": None,
        "official_source": "https://pmkusum.mnre.gov.in",
        "crops": ["all"],
        "states": ["all"],
        "keywords": ["solar", "pump", "energy", "electricity", "kusum"],
    },
    {
        "id": "enam",
        "name": "e-NAM (National Agriculture Market)",
        "category": "Market Access",
        "what": "An online trading platform connecting farmers to buyers across mandis (markets) so they can get better prices.",
        "eligibility": "Farmers who want to sell produce through integrated mandis. Registration required.",
        "benefit": "Access to a wider market, transparent price discovery and online payment for produce.",
        "documents": ["Identity proof", "Bank account details", "Mobile number"],
        "how_to_apply": "Register on the official e-NAM portal or at an e-NAM enabled mandi.",
        "deadline": None,
        "official_source": "https://www.enam.gov.in",
        "crops": ["all"],
        "states": ["all"],
        "keywords": ["market", "price", "sell", "mandi", "trade", "buyer"],
    },
    {
        "id": "kisan-rail",
        "name": "Agriculture Infrastructure Fund (AIF)",
        "category": "Infrastructure",
        "what": "A financing facility for building post-harvest management infrastructure and community farming assets (cold storage, warehouses, etc.).",
        "eligibility": "Farmers, FPOs, cooperatives, agri-entrepreneurs and startups. Verify eligible project types.",
        "benefit": "Interest subvention and credit guarantee support on loans for eligible agri-infrastructure projects (as per official guidelines).",
        "documents": ["Project proposal", "Identity & land/entity documents", "Bank details"],
        "how_to_apply": "Apply through the official Agriculture Infrastructure Fund portal or partner banks.",
        "deadline": None,
        "official_source": "https://agriinfra.dac.gov.in",
        "crops": ["all"],
        "states": ["all"],
        "keywords": ["storage", "warehouse", "cold storage", "infrastructure", "loan", "fund"],
    },
]

GUIDE_ARTICLES = [
    {
        "id": "crop-basics",
        "category": "Crop basics",
        "title": "Understanding crop growth stages",
        "body": "Every crop grows in stages: germination, vegetative growth, flowering, and fruiting or grain filling. Each stage needs different care. In the early vegetative stage, plants need enough water and nitrogen to grow leaves. During flowering, avoid water stress. Knowing the stage of your crop helps you decide when to irrigate, add nutrients, or watch for pests.",
    },
    {
        "id": "soil-basics",
        "category": "Soil basics",
        "title": "Knowing your soil type",
        "body": "Soil can be sandy, loamy, clayey or a mix. Sandy soil drains fast and dries quickly. Clay soil holds water but can get waterlogged. Loamy soil is a good balance and holds nutrients well. A simple check: wet a handful of soil and try to roll it. If it crumbles it is sandy; if it forms a sticky ball it has more clay. Match your irrigation to your soil type.",
    },
    {
        "id": "irrigation-basics",
        "category": "Irrigation basics",
        "title": "Watering your crop wisely",
        "body": "Water early in the morning or late evening to reduce evaporation. Check soil moisture by pushing a finger a few centimetres into the soil. If it feels dry, it may be time to water. Over-watering can cause root rot and yellow leaves, just like under-watering. Drip irrigation saves water and delivers it directly to the roots.",
    },
    {
        "id": "pest-awareness",
        "category": "Pest awareness",
        "title": "Spotting pests early",
        "body": "Check the underside of leaves regularly, where many pests hide. Look for holes, sticky residue, curling leaves, or tiny insects. Yellow sticky traps can help you notice pests early. Early detection means you can act before the problem spreads. Take a clear photo of any unusual symptom so you can compare over time or share it for advice.",
    },
    {
        "id": "plant-health",
        "category": "Plant-health observations",
        "title": "Reading plant symptoms",
        "body": "Yellow leaves can mean many things: too much water, too little water, nutrient shortage, or disease. Look at where the yellowing starts (old leaves vs new leaves) and whether it is spreading. Brown spots, wilting, or curling all tell a story. Record what you see with dates so you can notice patterns. When unsure, verify with a qualified agricultural professional.",
    },
    {
        "id": "farm-safety",
        "category": "Farm safety",
        "title": "Staying safe on the farm",
        "body": "Always read labels before using any farm chemical and wear gloves and a mask when spraying. Store chemicals away from food and out of reach of children. Wash your hands and change clothes after spraying. Keep first-aid items handy. Take breaks and stay hydrated during hot weather. Safe practices protect you and your family.",
    },
    {
        "id": "scheme-basics",
        "category": "Government-scheme basics",
        "title": "How to use government schemes",
        "body": "The government runs many schemes to support farmers: income support, crop insurance, credit cards, soil testing, and irrigation subsidies. Keep your Aadhaar, bank account and land records ready, as most schemes need them. Always apply through official portals or your local agriculture office. Scheme rules can change, so verify current eligibility and deadlines on the official government source before applying.",
    },
]
